name: Version Testing

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7']
        matplotlib-version: ['matplotlib==3.1', 'matplotlib==3.5']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Install Dependencies
        run: pip install ${{ matrix.matplotlib-version }}
      - name: Test with unittest
        run: |
          cd src/paxplot
          python test_core.py
          python test_datasets.py
